#!/bin/sh
#
# Nexus startup
#
# chkconfig: 2345 81 31
# description: Nexus daemon

### BEGIN INIT INFO
# Provides: nexus
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Should-Start: $named $time
# Should-Stop: $named $time
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Nexus startup
# Description: Nexus daemon
### END INIT INFO